# start services on random port by default
server:
  port: 0

# embedded database init, supports mysql too trough the 'mysql' spring profile
spring:
  sleuth:
    sampler:
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    refresh:
      refreshable: false
  profiles: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
    initialization-mode: ALWAYS

# Spring Boot 1.5 makes actuator secure by default
management:
  security:
    enabled: false

# Logging
logging:
  level:
    org:
      springframework: INFO
